[project]
name = "rag-example"
version = "0.1.0"
description = ""
authors = [
    {name = "mmahdi",email = "Aghajani@inside.sahab.ir"}
]
readme = "README.md"
requires-python = "3.10.19"
dependencies = [
    "langchain (==1.0.5)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel (==7.1.0)"
]
