[project]
name = "rag-example"
version = "0.1.0"
description = ""
authors = [
    {name = "mmahdi",email = "Aghajani@inside.sahab.ir"}
]
readme = "README.md"
requires-python = "3.10.19"
dependencies = [
    "langchain (==0.2.5)",
    "langchain-community (==0.2.5)",
    "llama-cpp-python (==0.2.78)",
    "sentence-transformers (==3.0.1)",
    "faiss-cpu (==1.8.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel (==7.1.0)",
    "ipywidgets (==8.1.8)"
]
